# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96609cdc9dedc667ab07c2ebc00fbe7fdb78aaf973c3018cb98b8b09cd05efeaea8a661f800e1aa9b1764338d686ef009d02dfac2283715acb762509ef08519

test:
  secret_key_base: be5ea5cb4fca1aa1f9227bd5c11d5eb93ca4be155375468626a5aed14c7669a4888272e366763f9e5e50202beec73c56a6d954df30330409b93416f6a74ed089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
